import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import "./globals.css";
// import Navbar from "@/components/NavBar/NavBar.js";
// import ModalWrapper from "@/components/NewsLetterModal/ModalWrapper";
// import ScrollTopButton from "@/components/ScrollTopButton";

export const metadata = {
  title: "Open Data Hub Charts",
  description: "Generated by john-papani",
  // icons: [
  //   {
  //     rel: "icon",
  //     type: "image/png",
  //     sizes: "32x32",
  //     url: "./favicons/favicon-32x32.png",
  //   },
  //   {
  //     rel: "icon",
  //     type: "image/png",
  //     sizes: "16x16",
  //     url: "./favicons/favicon-16x16.png",
  //   },
  // ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-sans text-black antialiased"
        suppressHydrationWarning={true}
      >
        {/* <ModalWrapper /> 
        <div>
          <ScrollTopButton />
        </div>
        <Navbar /> */}
        <div suppressHydrationWarning></div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
